ALTER TABLE tasks ADD COLUMN IF NOT EXISTS memory_mode TEXT NOT NULL DEFAULT 'with_memory';

ALTER TABLE evaluation_runs ADD COLUMN IF NOT EXISTS memory_hits INTEGER NOT NULL DEFAULT 0;
ALTER TABLE evaluation_runs ADD COLUMN IF NOT EXISTS repair_attempts INTEGER NOT NULL DEFAULT 0;
